version: '3.9'

services:
  redis:
    image: redis:latest
    restart: on-failure
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
      REDIS_USER_PASSWORD: redis
    ports:
      - '6379:6379'
    volumes:
      - './redis-data:/data/cacher'

  rabbitmq:
    image: rabbitmq:4-management
    restart: on-failure
    volumes:
      - './rabbitmq-data:/var/lib/rabbitmq'
    ports:
      - '5552:5552'
      - '5672:5672'
      - '15672:15672'

  pgsql:
    image: postgres:13.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai-crawler
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
