version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - './rabbitmq-data:/var/lib/rabbitmq'
    ports:
      - '5552:5552'
      - '5672:5672'
      - '15672:15672'

  pgsql:
    image: postgres:13.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ai-crawler
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'

  news-rss:
    image: news-rss:latest
    restart: unless-stopped
    links:
      - rabbitmq
      - pgsql
    ports:
      - '2895:2895'
    volumes:
      - './config:/app/config:ro'
    environment:
      NEWS_RSS_RUN_MODE: 'production'
