[logger]
level = "debug"

[server]
address = "0.0.0.0:2865"

[cache.local]
expired_secs = 360

[cache.redis]
address = "redis://localhost:6379"
username = "redis"
password = "redis"
expired_secs = 360

[publish.rmq]
address = "amqp://localhost:5672"
username = "rmq"
password = "rmq"
exchange = "news-rss-exchange"
routing_key = "news-rss-routing"
no_wait = true
durable = false

[publish.pgsql]
address = "localhost:5432"
database = "ai-crawler"
username = "postgres"
password = "postgres"
max_pool_size = 10

[storage.pgsql]
address = "localhost:5432"
database = "ai-crawler"
username = "postgres"
password = "postgres"
max_pool_size = 10

[crawler.llm]
api_key = "sk-no-key-required"
base_url = "http://localhost:8081/v1"
