[logger]
level = "info"

[server]
address = "0.0.0.0:2865"

[cache.local]
expired_secs = 10368000

[cache.redis]
address = "redis://redis:6379"
username = "redis"
password = "redis"
expired_secs = 10368000

[publish.rmq]
address = "amqp://rabbitmq:5672"
username = "rmq"
password = "rmq"
stream_name = "news-rss-stream"
exchange = "news-rss-exchange"
routing_key = "news-rss-routing"
capacity_gb = 1

[publish.pgsql]
address = "pgsql:5432"
database = "ai-crawler"
username = "postgres"
password = "postgres"
max_pool_size = 10

[storage.pgsql]
address = "localhost:5432"
database = "ai-crawler"
username = "postgres"
password = "postgres"
max_pool_size = 10

[crawler.llm]
api_key = "sk-no-key-required"
base_url = "http://llm:8081/v1"
