[logger]
level = "info"

[cache.local]
expired_secs = 10368000

[cache.redis]
address = "redis://redis:6379"
username = "redis"
password = "redis"

[publish.rmq]
address = "amqp://rabbitmq:5672"
username = "rmq"
password = "rmq"
stream_name = "news-rss-stream"
exchange = "news-rss-exchange"
routing_key = "news-rss-routing"
capacity_gb = 1

[publish.pgsql]
address = "pgsql:5432"
database = "ai-crawler"
username = "postgres"
password = "postgres"
max_pool_size = 10

[crawler.llm]
api_key = "sk-no-key-required"
base_url = "http://llm:8081/v1"

[topics.rss]
max_retries = 3
timeout = 100
interval_secs = 3600
source_name = "NDTV Worlds News"
target_url = "https://feeds.feedburner.com/ndtvnews-world-news"
